### ISSUE TITLE
Proposing to add #crane installation steps to the  OCM with flux  guide

### ISSUE THREAD

**Issue by mohammad-ammar14** [open-component-model/ocm-website#100]
**What would you like to be added**:
I would like to add the crane installation steps to the https://ocm.software/docs/guides/getting-started-with-ocm-flux/ guide.

MacOs:
$brew install crane

Linux:
sudo apt-get install crane
**Why is this needed**:
End user require crane to extract the deployment file.

**Comment by jensh007** [comment]
Do we really need crane as a requirement? The deployment.yaml can be downloaded with ocm?

**Comment by robertwol** [comment]
Closing, 
no part of the project. additional tools installation instructions are on relevant tools' pages.
this should sufficient for tech community,

Cheers
Robert
