### ISSUE TITLE
JSON schema public access

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm-website#13]
**What would you like to be added**:

The OCM spec should be retrievable via a well-known URI: https://json-schema.org/understanding-json-schema/structuring.html#base-uri

**Why is this needed**:

To ease access to the OCM spec.

**Comment by jensh007** [comment]
changed the id of the schema in https://github.com/open-component-model/ocm-spec/commit/c61525d8883cab4c548b186ce052b40757f7decd (see two files json-schema.yaml) to https://ocm.software/schemas/component-descriptor-v2 and https://ocm.software/schemas/component-descriptor-ocm-v3alpha1. Perhaps we should make the schemas available via this URL (or change it in the schema definition if this path is in appropriate).

**Comment by In-Ko** [comment]
> Perhaps we should make the schemas available via this URL (or change it in the schema definition if this path is in appropriate).
I think it makes sense to have "guessable" URIs from which the schema(s) could be retrieved.
- https://ocm.software/schemas/component-descriptor-v2 (which is the "CNUDIE" version) and
- https://ocm.software/schemas/component-descriptor-v3 (which is the "OCM" version).

Do we need a more specific versioning for the schemas ? The above indicates that we would use the major version (which is also mentioned within the schema itself under `meta - schemaVersion`)in the retrieval-URL, but what about minor or patch versions of a schema ?
