### ISSUE TITLE
Broken links in https://ocm.software/docs/guides/structuring-software-with-ocm/#introduction

### ISSUE THREAD

**Issue by fwilhe** [open-component-model/ocm-website#207]
**What happened**:

On https://ocm.software/docs/guides/structuring-software-with-ocm/#introduction, links are broken, for example https://github.com/open-component-model/ocm-spec/blob/main/doc/specification/elements/README.md#components and https://github.com/open-component-model/ocm-spec/blob/main/doc/specification/elements/README.md#artifacts lead to non-existing files in a github repo.

**What you expected to happen**:

Links in the docs should work.

**Comment by morri-son** [comment]
fixed with https://github.com/open-component-model/ocm-website/pull/220
