### ISSUE TITLE
Add "How to start with OCM" Guide to Website

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm-website#27]
**Description**
This Guide should cover the all necessary steps developers need to perform when they want to start making use of the OCM, like

- introducing component descriptors for their existing software components into their build processes
- how to manage new versions within the build process
- how to perform consistent transports to registries using the OCM CLI of single components and aggregated components
- ...

We should be using these examples as a starting point: https://github.com/open-component-model/ocm-spec/tree/main/example.

This "How to" guide should be used by newcomers as a starting point: Imagine someone totally new to OCM, and he/she just wants to try out the OCM CLI.

**Comment by mandelsoft** [comment]
some fixes and providements to support getting-started: https://github.com/open-component-model/ocm/pull/220

**Comment by mandelsoft** [comment]
prepare https://github.com/open-component-model/ocm-spec/pull/45

**Comment by jensh007** [comment]
Work-in-progress on pipeline-integration:
* reworked ocm-action repository (partly rewritten) and ocm-setup
* two samples provided for using github actions added to simpleserver sample

**Comment by mandelsoft** [comment]
conventions section added
