### ISSUE TITLE
Redesign the Website

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm-website#39]
**Description**
We should redesign the website a bit, to make it look more professional overall. This includes:
- integrating the new logo on the Website (suggestion: on the entry page, and on all subpages in the upper left corner)
- Agreeing on a font to be used on the site
- Adjusting the color palette of the website, to match the new logo (blue to dark grey)
- Restructure the entry page: Possibility to add some text on each of the three boxes (Describe, Transport, Deploy), each one should also be linking to a subpage.
- Set the FavIcon of the website to a mini representation of our new logo

**Comment by phoban01** [comment]
Here is the figma board for designs: https://www.figma.com/file/mF6T5Ep7cI3PmVlEaUkuJP/ocm-website?node-id=0%3A1&t=DNc0ymRtu2vldUXm-0

**Comment by In-Ko** [comment]
Quick summary of the initial discussion we had:

- integrating the new logo on the Website 
  - Big Logo on the Entry Page including the "Open Component Model" Text
  - Smaller Logo on every other page in the top left corner, also including the text
- Agreeing on a font to be used on the site
  - We will keep the font, but decrease the font size
- Adjusting the color palette of the website, to match the new logo (blue to dark grey)
  - Agreed on this one 
- Restructure the entry page: Possibility to add some text on each of the three boxes (Describe, Transport, Deploy), each one should also be linking to a subpage.
  - Also agreed on this one
- Set the FavIcon of the website to a mini representation of our new logo
  - nobrainer ;) , let's just do this
- Make the menu bar on the left collapsible and initially, only the "Overview" section should be expanded, everything else should be collapsed. 
- The content-area should be a bit wider
- The left menu bar should be a bit more separated from the content
- The header of the site needs rework, no transition from dark-grey to blue (or green as it is now). But somehow the header should be slightly separated from the rest, using a small line or a light background.

We also talked briefly about additional content, enabling the "blogs" feature again, as soon as we have a first nice article about the "birth of OCM", as well as a dedicated section outlining the "use cases" supported by OCM and its tools. But these content changes require some more discussions and of course content itself.

**Comment by In-Ko** [comment]
Just saw the work on the collapsible menu. Cool! One minor addition though: Could we add a simple indicator left to each menu entry to see if it is collapsed or not ? Similar to how you guys do it on https://fluxcd.io/flux/ ? I believe this would help the endusers to identify the current state of a menu entry.

**Comment by In-Ko** [comment]
As discussed on Friday, all we need is some kind of indicator on the menu links, to show the user that these are clickable. So slight change in color when the mouse is hovering over a menu entry could already be enough, does not have to be such an indicator (triangle) as commented above.
