### ISSUE TITLE
URL typo in README.MD

### ISSUE THREAD

**Issue by cruschke** [open-component-model/ocm-website#82]
**What happened**:
The URL in
> This repository houses the assets used to build [Open Component Model website](https://ocm.sofware/).

is broken, there is a _t_ missing in software.

**What you expected to happen**:
a working link :-) 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by robertwol** [comment]
solved
