### ISSUE TITLE
Generated OCM CLI Documentation on Website shows markup

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm-website#89]
**Description**
The CLI Documentation shown on the website (e.g. here: https://ocm.software/docs/cli/add/componentversions/) seems to have some generation issues, as some of the documentation pages show markup (like `<pre>`, which can be seen in https://ocm.software/docs/cli/add/componentversions/). The generation source files look ok (see here: https://github.com/open-component-model/ocm/blob/main/docs/reference/ocm_add_componentversions.md)

This has to be fixed, before we get more traffic on the website (due to the GitOpsCon talks for example).

**Comment by jensh007** [comment]
added PR #101 to fix this issue.
