### ISSUE TITLE
Steps in getting-started-with-ocm-flux incorrectly assume pwd

### ISSUE THREAD

**Issue by dee0sap** [open-component-model/ocm-website#91]
In 
https://ocm.software/docs/guides/getting-started-with-ocm-flux/#setting-up-our-project
you are instructed to run 
_ocm add componentversions --create --file ./component-archive components.yaml_
and then some output from
_tree ._
is shown 

However if you run the above commands back to back the output doesn't match what is in the doc.   Basically the doc assumes that you first cd into component-archive

**Comment by robertwol** [comment]
Hi @dee0sap 
The documentation was updated, please could you confirm if you still observe discrepancies.
Cheers
Robert
