### ISSUE TITLE
https://ocm.software/docs/guides/getting-started-with-ocm-flux/#signing steps key gen, usage inconsistentb

### ISSUE THREAD

**Issue by dee0sap** [open-component-model/ocm-website#92]
The command 
_ocm create rsakeypair_
creates these two files 
_keypair      keypair.pub_

But then the next command mentioned in the doc 
_ocm sign component --signature alice --private-key rsa.priv --public-key rsa.pub ./component-archive_
is assuming that rsa.priv was created by the previous command.

**Comment by robertwol** [comment]
Hi @dee0sap 
the documentation was improved since then. please could you confirm if this is still relevant?
Cheers
Robert

**Comment by dee0sap** [comment]
Better now, thanks!
