### ISSUE TITLE
https://ocm.software/docs/guides/getting-started-with-ocm-flux/ doesn't make clear what env vars should be set

### ISSUE THREAD

**Issue by dee0sap** [open-component-model/ocm-website#93]
NOTE: Maybe I am an impatient person not taking full time to carefully read the doc word by word but probably that is normal

The doc refers to some env vars, e.g. $GITHUB_USER.   

Searching the page for 'user' I don't find anything that lets me know this env var should be set.
And searching for 'env' I don't find a list of environment variables I should set.

If I am going to build some sort of automation around this doc it would be good if it provided a list of env vars I should set.

**Comment by phoban01** [comment]
Closing as we have updated the guides.
