### ISSUE TITLE
Crane usage on getting-started-with-ocm-flux seems incorrect.

### ISSUE THREAD

**Issue by dee0sap** [open-component-model/ocm-website#95]
In this section 
https://ocm.software/docs/guides/getting-started-with-ocm-flux/#reconciling-components

The output from 
kubectl describe snapshot podinfo-deployment -n ocm-system | grep "Repository URL:"
doesn't seem to provide everything you need for crane and it doesn't match what is in the doc.

I found I had to do this 
kubectl get snapshot podinfo-deployment -n ocm-system -o=yaml | grep -Ei 'url|digest'
to get what I need

```
podinfo/crane # kubectl get snapshot podinfo-deployment -n ocm-system -o=yaml | grep -Ei 'url|digest'
  digest: sha256:c0323f691567e471f5bb5bbef5acccc8fb8a90371c09a16523b1f06952bc02ae
  digest: sha256:c0323f691567e471f5bb5bbef5acccc8fb8a90371c09a16523b1f06952bc02ae
  repositoryURL: http://registry.ocm-system.svc.cluster.local:5000/sha-6755120779484647029

```

With the above about I was able to build the following command 

`/crane blob registry.ocm-system.svc.cluster.local:5000/sha-6755120779484647029@sha256:c0323f691567e471f5bb5bbef5acccc8fb8a90371c09a16523b1f06952bc02ae > blob.tar
`
Note that with out the digest crane issues an error like 

`Error: pulling layer registry.ocm-system.svc.cluster.local:5000/sha-6755120779484647029: a digest must contain exactly one '@' separator (e.g. registry/repository@digest) saw: registry.ocm-system.svc.cluster.local:5000/sha-6755120779484647029
`

Additionally I found I had to gunzip the output from crane before I could pass it to tar.

**Comment by phoban01** [comment]
Closing as we have updated the guides.
